name: GitHub Workflow  

on:
 workflow_run:
   workflows: "package-A"
   branches: main
   types:
     - completed


jobs:

  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:

      - name: Create a temporary artifact downloads folder
        run: mkdir downloads
        
      - name: Add artifacts to publish to the temp folder
        run: |
          cd downloads
          echo 'beta'    > beta.html
          cd ..
    
      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: downloads
          
     
