name: GitHub Workflow  

on:
 workflow_run:
   workflows: "Create Artifact Package-A"
   branches: main
   types:
     - completed


jobs:

  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:

      - name: Create a temporary artifact downloads folder
        run: mkdir downloads
      name: Download and List Artifact from Another Repository

on:
  push:
    branches:
      - main

jobs:
  download-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          repository: cs1867/package-A
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: List downloaded files
        run: |
          ls -l
          
      - name: Add artifacts to publish to the temp folder
        run: |
          cd downloads
          echo 'beta'    > beta.html
          cd ..
    
      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: downloads
          
     
