name: Download Release

# Controls when the workflow will run
on: push

jobs:

  
  get_asset:

    runs-on: ubuntu-latest

    steps:

      - name: List Releases
        run: gh release list --repo  https://github.com/cs1867/package-A
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}

      - name: Fetch asset
        run: gh release download --repo cs1867/ *.zip --archive=zip
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}

      - name: See what we downloaded
        run: ls

      - name: Inspect content
        run: cat hello.txt
