name: Downloan Artifacts 

on:
  workflow_dispatch:
  push:
    branches: [ main ]
 
jobs:
       
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - name: display structure of downloaded files
        run: ls -R
        
 
