name: Downloan Artifacts 

on:
  workflow_dispatch:
  push:
    branches: [ main ]
 
jobs:
       
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      
      - name: Download artifact from repo-B
        uses: actions/download-artifact
        with:
          name: repo-A
          path: downloads
          repository: package-A
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      
      - name: display structure of downloaded files
        run: ls -R
        
 
