name: Download and List Artifact from Another Repository

on:
  push:
    branches:
      - main

jobs:
  download-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: repo-A
          repository: cs1867/package-A
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: List downloaded files
        run: |
          ls -l
