# Publish GitHub workflow artifacts tutorial example
name: Publish GitHub Actions Artifacts Example

on:
  push:
    branches: [ main ]

jobs:
       
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:

      - name: Step 1 - Create a temporary artifact downloads folder
        run: mkdir downloads
        
      - name: step 2 - Add artifacts to publish to the temp folder
        run: |
          cd downloads
          echo 'beta'    > beta.html
          cd ..
    
      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: downloads
          

      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "downloads/*"
          target: "/tmp/"
