name: Publish GitHub Actions Artifacts 

on:
  workflow_dispatch:
    inputs:
      var1:
        description: 'Description of var1'
        required: true
  push:
    branches: [ main ]
   
jobs:

       
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Print received variables
        run: |
         echo "Variable 1: ${{ github.event.inputs.var1 }}"
      
      - name: Create a temporary artifact downloads folder
        run: mkdir downloads
        
      - name: Download artifact from repo-A
        uses: actions/download-artifact@v4
        with:
          name: repo-A
          repository: cs1867/package-A
          path: downloads
          github-token: ${{ secrets.GIT_ACTIONS }}
          run-id: ${{ github.event.inputs.var1 }}
      
      - name: Display structure of downloaded files
        run: |
          ls -R 
          pwd

      - name: Add artifacts to publish
        run: |
          cd downloads
          ls -al 
          echo "cat alpha"
          cat alpha.html
          echo "now create beta"
          echo 'beta'    > beta.html
          cat beta.html
          echo "now add alpha"
          cat alpha.html >> beta.html
          cat beta.html
          ls -al 
          cd ..
    
      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: repo-B
          path: downloads
          
 
