name: Publish GitHub Actions Artifacts 

on:
  workflow_dispatch:
    inputs:
      packageA:
        description: Package A Git Run ID'
        required: true
      packageB:
        description: Package B Git Run ID'
        required: true
  #push:
  #  branches: [ main ]
   
jobs:

       
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Print received variables
        run: |
         echo "Package B : ${{ github.event.inputs.packageA }}"

      - name: Print received variables
        run: |
         echo "Package B : ${{ github.event.inputs.packageB }}"
      - name: Create a temporary artifact downloads folder
        run: mkdir downloads
        
      - name: Download artifact from repo-A
        uses: actions/download-artifact@v4
        with:
          name: repo-A-RHEL
          repository: cs1867/package-A
          path: downloads
          github-token: ${{ secrets.GIT_ACTIONS }}
          run-id: ${{ github.event.inputs.packageA }}
      
      - name: Display structure of downloaded files
        run: |
          ls -R 
          pwd

      - name: Add artifacts to publish
        run: |
          echo "now create beta"
          cd downloads
          echo "ls the dir"
          ls -al 
          echo "create file and add alpha"
          cat alpha.html > beta.html
          echo "add RHEL beta to the file"
          echo 'RHEL beta' >> beta.html
          echo "cat beta"
          cat beta.html
          echo "list the dir"
          ls -al 
          cd ..
    
      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: repo-B-RHEL
          path: downloads/beta.html
          
 
